Remove quickemu override
It was giving this error after flake.lock update:

error: function 'anonymous lambda' called with unexpected argument 'qemu'

Maybe it always requires qemu_full now?